### ISSUE TITLE
Developer & Mentors need Travis-ci

### ISSUE THREAD

**Issue by jenpaff** [systers/powerup-iOS#100]
## Description
As a developer and mentor, I want our code to be integrated with a continuous integration and build system to ensure code quality and make code reviews easier for both mentors and developers.  

## Acceptance Criteria
- setting up and configuring Travis-ci build management system
- Travis-ci integrated with github 
- Current repo builds successfully

## Definition of Done
-Passes user testing per acceptance criteria items.
-Successful build based on latest version
-Approval by mentors 

## Estimation

**Comment by casd82** [comment]
Completed in PR #102. It should be merged first so other PRs could succeed the automated test.
