### ISSUE TITLE
Add contextual labels to each screen

### ISSUE THREAD

**Issue by madeleine-b** [systers/powerup-iOS#11]
Like "Map/Journey", "iPod Troubles", etc.

**Comment by jenpaff** [comment]
@madeleine-b Can you please give a more detailed description of this issue?

**Comment by madeleine-b** [comment]
@jenpaff It's been a little while since I looked at the app, but from what I recall, I meant that it would be helpful to have a label on every screen reminding the user what scenario they're playing or if they're looking at the map or avatar customization screen, etc. I think this could also help with accessibility so that someone using a screen reader would always know where they were in the app.

**Comment by lovett2** [comment]
I'll take a look at this.
