### ISSUE TITLE
Some error message text needs minor fix

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#112]
1 - restarting is misspelled:
CustomizeAvatarViewController, in func saveAvatar()

2 - There is no suggested action on one of the errors in ResultsViewController. Add the same suggestion as for the other errors.

**Comment by vatsalkulshreshtha** [comment]
Fixed Error Message text. https://github.com/systers/powerup-iOS/pull/174

**Comment by akshaynexus** [comment]
#175 Fixed spelling errors and other fixes
