### ISSUE TITLE
Mentors want Travis status added to repository

### ISSUE THREAD

**Issue by jenpaff** [systers/powerup-iOS#118]
## Description
As a mentor, I want to see the Travis status, to see straight away whether the build passed or failed

## Mocks
![travis_status](https://user-images.githubusercontent.com/5339211/28623998-fa56a5b4-7217-11e7-945a-c6b6022b678f.jpg)

## Acceptance Criteria
- Travis status added to repo

## Definition of Done
- Travis status added to repo shows correctly

## Estimation
2hrs

**Comment by sunjunkie** [comment]
Done - PR #119
