### ISSUE TITLE
Create new avatar screen extends beyond iPhone 5 screen

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#128]
This screen extends beyond the edge of the iPhone 5 screen so one of the buttons is off the screen. See attached screen shot.

![simulator screen shot aug 14 2017 3 41 36 pm](https://user-images.githubusercontent.com/399376/29295176-d6039218-8107-11e7-9919-738c35a6b2fb.png)

**Comment by justKD** [comment]
The UI for character creation has changed considerably! I think this is an old issue that can be closed.

<img width="589" alt="screen shot 2018-05-01 at 10 43 11 am" src="https://user-images.githubusercontent.com/24572031/39479992-8575cb62-4d2c-11e8-954d-be748775242c.png">
