### ISSUE TITLE
Users should be able to revert and try out different accessories in Shop Scene.

### ISSUE THREAD

**Issue by casd82** [systers/powerup-iOS#129]
Users should be able to click on several accessories of the same type when shopping without karma points being deducted for each click, so that they see how each accessory of that type looks and decide which one they like better.

(Previous commits may contain existing code for this issue. Look at `ShopViewController.swift` in: https://github.com/systers/powerup-iOS/pull/98/commits/d1c955461a026943db827ef50438f2977c7484f6)

**Comment by erikaaatan** [comment]
@sunjunkie I will start working on this issue
