### ISSUE TITLE
Mini Game Content needs Clean Up before Release.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-iOS#130]
## Description
As a tester,
I want to test content in a quick manner,
so that I can make notes and open bugs when appropriate.

## Mocks
![screen shot 2017-08-18 at 4 43 43 pm](https://user-images.githubusercontent.com/2440938/29477003-715014c4-8434-11e7-9947-025250c290e7.png)

## Acceptance Criteria
- All mini games have generic test questions with the answer clearly written. For example, "Test Question #9, Answer: False" (as shown above in mock)
1. Minesweeper (when appropriate)
2. Sink to Swim
3. Vocab Match Game

## Definition of Done
- Approved by May (set up a quick 15 min hangout to review all games)

## Estimation
2 hours

**Comment by casd82** [comment]
Hi @MeepyMay, I think the texts for all the mini games are already generic and good for testing.

## Minesweeper
I use mock description text when each round ends.
![simulator screen shot 2017 8 21 1 10 29](https://user-images.githubusercontent.com/12479866/29504966-ea712396-8675-11e7-842d-265cdc65c0a8.png)

## Sink to Swim
I use 10 mock questions with answers shown clearly:
```
var questions: [SinkToSwimQuestion] = [
        SinkToSwimQuestion(description: "Test question 1, answer: true", correctAnswer: true),
        SinkToSwimQuestion(description: "Test question 2, answer: false", correctAnswer: false),
        SinkToSwimQuestion(description: "Test question 3, answer: false", correctAnswer: false),
        SinkToSwimQuestion(description: "Test question 4, answer: true", correctAnswer: true),
        SinkToSwimQuestion(description: "Test question 5, answer: false", correctAnswer: false),
        SinkToSwimQuestion(description: "Test question 6, answer: false", correctAnswer: false),
        SinkToSwimQuestion(description: "Test question 7, answer: false", correctAnswer: false),
        SinkToSwimQuestion(description: "Test question 8, answer: true", correctAnswer: true),
        SinkToSwimQuestion(description: "Test question 9, answer: false", correctAnswer: false),
        SinkToSwimQuestion(description: "Test question 10, answer: false", correctAnswer: false)
]
```

## Vocab Matching
I use the tiles provided by Kim, and the texts in clipboards are understandable for testers.
![simulator screen shot 2017 8 21 1 10 45](https://user-images.githubusercontent.com/12479866/29505066-62d9bca8-8676-11e7-8b95-a641189c3fa4.png)

Do I still need to change anything?

**Comment by MeepyMay** [comment]
@casd82 This looks good! Perfect for testing.

Do you have any additional slang in the scenarios? I found a "Darling" in Android. Are there any additional words that are not necessary?

**Comment by casd82** [comment]
@MeepyMay I don't think there are any additional slangs left in iOS.

**Comment by MeepyMay** [comment]
Thank you for checking @casd82 !
