### ISSUE TITLE
The avatars of Shop, Scenario, and Customize Avatar scene should be scaled up.

### ISSUE THREAD

**Issue by casd82** [systers/powerup-iOS#132]
The size of the avatars and the accessories should be scaled up to match to size of the Android version.

Current size:
<img width="729" alt="ios" src="https://user-images.githubusercontent.com/12479866/29758077-3fa8c144-8be3-11e7-84d9-c121462b27e7.png">

Should be:
<img width="479" alt="android" src="https://user-images.githubusercontent.com/12479866/29758082-48d63800-8be3-11e7-8d59-d1d972a9b970.png">

**Comment by justKD** [comment]
It looks like the Android version is just scaling the images differently. The aspect ratio seems off. I'm just guessing, but it kind of looks like the images are being told to fill the view rather than scale to aspect ratio, which it seems the iOS version is doing.

**Comment by sunjunkie** [comment]
We should scale to aspect ratio so closing this.
