### ISSUE TITLE
Fix the about screen.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-iOS#137]
## Description
As a user,
I don't need to edit the about details,
so that I can read freely.

## Mocks
N/A

## Acceptance Criteria
1. Content is not editable.
2. Content is scrollable.

## Definition of Done
- Approved by 1 mentor in GHC OSD

## Estimation
1 hours

**Comment by Adeti** [comment]
You could also make the content more user-friendly; Change the format of the Sub-heading to differentiate between the heading and their description.

**Comment by g30r93g** [comment]
Fixed. Just a matter of unchecking the 'editable' box in the attributes inspector. The following link has the new code: https://github.com/g30r93g/powerup-iOS

**Comment by vatsalkulshreshtha** [comment]
# Fixed
Just by unchecking the "Editable" box in attribute inspector. https://github.com/systers/powerup-iOS/pull/173
Screenshot:

![screen shot 2017-12-15 at 2 32 35 pm](https://user-images.githubusercontent.com/34273246/34034654-5e8af8e4-e1a5-11e7-9181-38ce6c9f4c60.png)

**Comment by akshaynexus** [comment]
https://github.com/systers/powerup-iOS/pull/177
