### ISSUE TITLE
Update for xcode 9, swift 4, and ios 11

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#141]
**Description**

As a user,
I want to be able to run the app on the latest version of iOS
so that I can use it on a new or updated iPhone .

**Mocks**

N/A

**Acceptance Criteria**

App can be built sucessfully with no errors or warning in xcode 9 using swift 4.
App will run successfully on iOS 11.

**Definition of Done**

Approved by 1 mentor in GHC OSD

**Estimation**

2 hours

**Comment by vatsalkul** [comment]
I MIGRATE THE PROJECT TO SWIFT 4 IN POWERUP IOS. PR link: https://github.com/systers/powerup-iOS/pull/153

**Comment by vatsalkul** [comment]
Please go through this PR link, I migrated the project to Swift 4, to provide new code.
https://github.com/systers/powerup-iOS/issues/141

**Comment by vatsalkul** [comment]
I migrate the project to swift 4. Please follow this PR https://github.com/systers/powerup-iOS/pull/154

**Comment by vatsalkulshreshtha** [comment]
I Vatsal Kulshreshtha migrated the Powerup iOS project to Swift 4.
PR : https://github.com/systers/powerup-iOS/pull/156

**Comment by vatsalkulshreshtha** [comment]
Please go through this link. I migrated the project to swift 4. Hope it will help

**Comment by vatsalkulshreshtha** [comment]
Migrated to swift 4. https://github.com/systers/powerup-iOS/pull/159

**Comment by vatsalkulshreshtha** [comment]
Migrated to swift 4 https://github.com/systers/powerup-iOS/pull/160

**Comment by akshaynexus** [comment]
Upgraded code from siwft 3 to swift 4 -> #179

**Comment by akshaynexus** [comment]
upgraded to swift 4 #185

**Comment by fkiwitt** [comment]
Hey everyone,
I have created another PR (for google code in). If you want to you can check it out here: https://github.com/systers/powerup-iOS/pull/198
