### ISSUE TITLE
Text getting cut off by the ui bounds

### ISSUE THREAD

**Issue by hasiniran** [systers/powerup-iOS#143]
When dialogs are displayed, the text is getting cut off by the view bounds. Check the attached images.

<img width="1023" alt="screen shot 2017-11-25 at 4 36 33 pm" src="https://user-images.githubusercontent.com/9370429/33235134-20ea7d8e-d200-11e7-90ca-49d2031af180.png">
<img width="565" alt="screen shot 2017-11-25 at 4 34 51 pm" src="https://user-images.githubusercontent.com/9370429/33235135-20f95804-d200-11e7-8b56-ac053f06a066.png">

If the text is too long to fit to the current view, either text fonts or enclosing view need to be resized.

**Comment by vatsalkul** [comment]
You can refer to this PR link: https://github.com/systers/powerup-iOS/pull/146
