### ISSUE TITLE
Text appears outside the button bounds in ShopViewController

### ISSUE THREAD

**Issue by hasiniran** [systers/powerup-iOS#144]
In ShopViewController, the text 'select' spans beyond the button rectangle. 

<img width="982" alt="screen shot 2017-11-25 at 4 58 29 pm" src="https://user-images.githubusercontent.com/9370429/33235295-641171f0-d203-11e7-9179-6b56a9ed11f3.png">

**Comment by vatsalkulshreshtha** [comment]
I improved the appearance of the "Select" in ShopViewController. Please go to this PR link https://github.com/systers/powerup-iOS/pull/161

**Comment by vatsalkulshreshtha** [comment]
I improved the appearance of the "Select" in ShopViewController. Please go to this PR link https://github.com/systers/powerup-iOS/pull/162

iPad (5th generaation)
![screen shot 2017-12-06 at 4 22 55 pm](https://user-images.githubusercontent.com/34273246/33658256-0d884da2-daa2-11e7-896e-0b2ad93a9e45.png)

iPhone 8
![screen shot 2017-12-06 at 4 20 33 pm](https://user-images.githubusercontent.com/34273246/33658277-20cf25de-daa2-11e7-9c95-aa48ba43b39d.png)


iPhone 5s
![screen shot 2017-12-06 at 4 17 34 pm](https://user-images.githubusercontent.com/34273246/33658286-29381942-daa2-11e7-8c02-b6350b8a45ff.png)

**Comment by vatsalkul** [comment]
Solved: Hide empty display boxes in ShopViewController. PR https://github.com/systers/powerup-iOS/pull/187

**Comment by sunjunkie** [comment]
This is an iPad issue and iPad support is TBD.
