### ISSUE TITLE
Add a 1024x1024 app icon to the project

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#164]
The latest iTunes App Store requires a 1024x1024 png file to use as the store app icon to be part of the compiled project. So this file needs to be added to the image assets in Xcode.
![appicon1024](https://user-images.githubusercontent.com/399376/33677845-fe8e345c-da6e-11e7-8819-903cc6fb4f2c.png)

**Comment by vatsalkulshreshtha** [comment]
I added a 1024x1024 app icon. https://github.com/systers/powerup-iOS/pull/167
