### ISSUE TITLE
Force new user when played for the first time

### ISSUE THREAD

**Issue by jenpaff** [systers/powerup-iOS#17]
DevChange made in Android App:

When the app starts for the first time, the user should be directed to the changing room directly

**Comment by sanyajain** [comment]
Already implemented in PR #21. When user clicks 'New User' on Start Screen,user is directed to Dressing Room-1 directly. 
When the app is launched for the first time, user is forced to hit New User first. If user clicks Start, an alert message pops up directing user to hit New User first. This is implemented in PR #28
