### ISSUE TITLE
Improvements in the CustomizeAvatarViewController are required for larger screen sizes

### ISSUE THREAD

**Issue by hasiniran** [systers/powerup-iOS#170]
Buttons and avatar look mis-positioned for larger screen sizes (iPad).  Following images show how the 'Customiz Avatar' view appears in iPhone 8 and iPad respectively. Identified mis-positioned are mark red for the iPad. 

_iPhone 8_
<img width="702" alt="screen shot 2017-12-09 at 9 05 47 pm" src="https://user-images.githubusercontent.com/9370429/33801411-a0c9bc80-dd28-11e7-99c9-b20ebc727362.png">

_iPad_
<img width="1009" alt="screen shot 2017-12-09 at 9 20 54 pm" src="https://user-images.githubusercontent.com/9370429/33801417-cf7c4020-dd28-11e7-902f-24d25672a69a.png">

**Comment by vatsalkulshreshtha** [comment]
I wanna ask that how the Continue Button is mispositioned.

**Comment by hasiniran** [comment]
Compare with how the button is positioned in the storyboard and under small screen sizes.

**Comment by vatsalkulshreshtha** [comment]
Improved 'Customize Avatar' view for iPad. https://github.com/systers/powerup-iOS/pull/176

**Comment by vatsalkulshreshtha** [comment]
@hasiniran Please check this Issue https://github.com/systers/powerup-iOS/issues/193 I want you to add the following points in this issue and then I’ll close that one.
Can I work on this after you merged the issue and update my PR https://github.com/systers/powerup-iOS/pull/176

**Comment by sunjunkie** [comment]
Closing this since iPad support is TBD.
