### ISSUE TITLE
Suggestion: Hide empty display boxes in ShopViewController

### ISSUE THREAD

**Issue by hasiniran** [systers/powerup-iOS#188]
## Description

ShopViewController displays an empty grayed-box for hair, clothes and accessaries that do not exist. For example, go to Store -> Clothes. You will notice only the first display box is non-empty and other boxes are empty. Improvement for this view to hide the display boxes if the box content ( hair/cloth/accessary) is empty would be a better way of displaying. 

## Mocks

Current view:

<img width="752" alt="screen shot 2018-01-06 at 3 45 59 pm" src="https://user-images.githubusercontent.com/9370429/34638765-c05839d8-f2f8-11e7-979b-f56debbbacd4.png">

Expected view:

<img width="737" alt="screen shot 2018-01-06 at 3 43 26 pm" src="https://user-images.githubusercontent.com/9370429/34638767-c90f48c8-f2f8-11e7-917c-cd20c990e4ab.png">

**Comment by fkiwitt** [comment]
I just did another PR for Google Code In: https://github.com/systers/powerup-iOS/pull/189

**Comment by Nate-Gaudreault** [comment]
Completed the task in PR #191

**Comment by Nate-Gaudreault** [comment]
Resolved the issue for GCI in PR #194

**Comment by sunjunkie** [comment]
The merged PR causes tests to fail; reopening this issue.
