### ISSUE TITLE
With a new user, app uses previous data

### ISSUE THREAD

**Issue by imaculate** [systers/powerup-iOS#19]
I think it a user , starts a new user ,it should start with a clean slate, not remembering where the previous user left off.

**Comment by imaculate** [comment]
@chhavip Can I go ahead with this?

**Comment by chhavip** [comment]
@imaculate, this is power up iOS repository, I am reviewer for the android one, please reach out to iOS reviewers.

**Comment by sunjunkie** [comment]
Fixed via PR #74
