### ISSUE TITLE
CONTRIBUTING_GUIDELINES.md need edits

### ISSUE THREAD

**Issue by samyukthacodes** [systers/powerup-iOS#190]
## Description
Edit the markdown and to beautify the documentation.

## Definition of Done
- [ ] Approval by 1 mentor.

**Comment by samyukthacodes** [comment]
Can I take up this issue?

**Comment by samyukthacodes** [comment]
@dawnchandler Can I take up this issue?

**Comment by dawnchandler** [comment]
Yes, please do. I am transitioning out of GCI mentorship.

**Comment by MeepyMay** [comment]
We're following a template used for every repo in the Systers open source org.
