### ISSUE TITLE
Move strings to separate file

### ISSUE THREAD

**Issue by dimuth** [systers/powerup-iOS#210]
## Description
As a developer, I need to use strings from a separate file to avoid duplications. As well as, a user I need to use the app with my own language. Therefore we need to implement localization feature in future and this restructuring will help us to implement localization. We could create a separate file (Strings.swift) and move all strings to that file to make this localization process easier.

## Acceptance Criteria
All the strings in app will be moved to a separate file as localizable strings.

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by SIMRAN1** [comment]
@dimuth  I want to work on this issue..May I start working on it.

**Comment by sunjunkie** [comment]
@SIMRAN1 Yes, this is a good practice for localization.

**Comment by dimuth** [comment]
@SIMRAN1 
Seems your Strings.swift file does not help for localisation.

**Comment by SIMRAN1** [comment]
@dimuth what enhancements should I do?

**Comment by dimuth** [comment]
@SIMRAN1 
Better to use `NSLocalizedString` for your String file. Then we can use it later for localisation. Therefore we can use that file for avoid duplication and implement localisation.

**Comment by SIMRAN1** [comment]
okk thanks I will see this approach!
