### ISSUE TITLE
Suggestion: Change purchase warning message

### ISSUE THREAD

**Issue by erikaaatan** [systers/powerup-iOS#215]
## Description
As a user,
I might be confused about the purchase warning message,
which says that I will be spending x amount of dollars. 
(This might cause confusion about whether the user is making an in-app purchase, or it might not be what the user's currency is called in her home country.)

## Mocks
<img width="745" alt="screen shot 2018-02-18 at 10 37 36 pm" src="https://user-images.githubusercontent.com/34075473/36361716-5634e6fc-14fc-11e8-858f-ad024784063c.png">

## Acceptance Criteria
Part of the message should be changed so that it reads "You will be spending x karma points" rather than "You will be spending $x".

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by erikaaatan** [comment]
@sunjunkie If this is approved I will send in a PR for it

**Comment by Tagsahil** [comment]
I am already sent PR for this change

**Comment by Tagsahil** [comment]
@sunjunkie check this out.
