### ISSUE TITLE
Adding Segue identifiers to a Seprate class Constants.swift

### ISSUE THREAD

**Issue by SIMRAN1** [systers/powerup-iOS#219]
## Description
Adding segue identifier into Seprate class..All the segue identifiers will be moved to constants.swift.

## Estimation
2 hours 
@sunjunkie @MeepyMay What's say about it?.
I want to work on this issue.

**Comment by sunjunkie** [comment]
Take a look at this approach: https://www.bignerdranch.com/blog/using-swift-enumerations-makes-segues-safer/ using enums (and extensions to each view controller)

**Comment by SIMRAN1** [comment]
@sunjunkie  I will see this approach and send a pr for this!
