### ISSUE TITLE
2nd level should be opened after completing 1st level

### ISSUE THREAD

**Issue by jenpaff** [systers/powerup-iOS#22]

**Comment by YashBit** [comment]
Can this task please be assigned to me ?

**Comment by YashBit** [comment]
@jenpaff  Can this task please be assigned to me ?

**Comment by sanyajain** [comment]
Hello @YashBit ! Yeah, you can assign this issue to yourself if you want to work for it :)

**Comment by YashBit** [comment]
@sanyajain I will solve the bug of the disappearing UI image .
Could you please send a link to a BUG task for PWR ?
Thanks .

**Comment by YashBit** [comment]
@sanyajain  If the code is okay ,why wasn't the PR merger (Just Curious :) ! )

https://github.com/systers/powerup-iOS/pull/39

**Comment by sanyajain** [comment]
@YashBit I will ask others also to review the code (just to be sure!) and then the PR will be merged.
