### ISSUE TITLE
Confirm label colour is not visible properly in CustomisedAvatarViewController

### ISSUE THREAD

**Issue by Tagsahil** [systers/powerup-iOS#223]
## Description
In Confirm Label colour is not visible properly because of background colour.

## Mocks
![screen shot 2018-02-28 at 5 26 41 pm](https://user-images.githubusercontent.com/31792015/36798127-bf637dca-1ccf-11e8-94e9-c133d5525bc4.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours 
I want to work on it.

**Comment by Tagsahil** [comment]
I want to work on it.

**Comment by sunjunkie** [comment]
The text color was decided upon as part of the app design that’s been done so far. To change this to a different color will require further discussion among project owners.

**Comment by Tagsahil** [comment]
but this changes approved by mentor. @sunjunkie
