### ISSUE TITLE
Fix Vocab Match end screen

### ISSUE THREAD

**Issue by erikaaatan** [systers/powerup-iOS#224]
## Description
As a user,
when I finish the Vocab Match mini game,
the end screen does not fit in with the overall design of the app.

### iOS Vocab Match end screen
![image](https://user-images.githubusercontent.com/34075473/36813540-f16b1198-1ca2-11e8-9892-7da47f512d9a.png)
### Android Vocab match end screen
![image](https://user-images.githubusercontent.com/34075473/36813561-fc661084-1ca2-11e8-82fc-819d927e6bb6.png)

## Acceptance Criteria
The Vocab Match end screen looks like the end screen in the Android version.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by sunjunkie** [comment]
@erikaaatan Approved.
