### ISSUE TITLE
Update karma points based on mini game score

### ISSUE THREAD

**Issue by erikaaatan** [systers/powerup-iOS#229]
## Description
As a user,
I would like to earn karma points from the mini games,
so that I can buy more things.
Also, this feature would make it more consistent with the Android app because it currently gives additional karma points based on the user's mini game score.

## Mocks
In the Android version, the user gains more karma points when she plays the mini games, as opposed to when she doesn't.
#### Playing the mini game
![screenshot_1519955503](https://user-images.githubusercontent.com/34075473/36879633-cb2f3e82-1d92-11e8-8e5d-fead81f80f75.png)
#### Not playing the mini game
![screenshot_1519955722](https://user-images.githubusercontent.com/34075473/36879661-e0991716-1d92-11e8-8966-8ffbf4737411.png)

## Acceptance Criteria
The mini game score is added to the user's karma points. If the user replays the scenario, the karma points previously gained from the scenario should be reset, like in the Android version. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by erikaaatan** [comment]
@sunjunkie If this is approved I will start working on it

**Comment by sunjunkie** [comment]
Approved @erikaaatan
