### ISSUE TITLE
Create a Continue Button 

### ISSUE THREAD

**Issue by Tagsahil** [systers/powerup-iOS#233]
## Description
As a user if I complete a scenario and I want move to next scenario i need a button which can directly move me to next scenario.
In now's iOS application continue button is not there.
So,if I want to move next scenario i just go to map and from there I will move to next scenario.
So,we have to add Continue Button.
In android there is continue button.

 

## Mocks

![screen shot 2018-03-03 at 8 59 56 pm](https://user-images.githubusercontent.com/31792015/36947635-e2036b1a-1ff4-11e8-81ab-9f1b403ce7a9.png)

## Acceptance Criteria

It should be look like android app.
![screen shot 2018-03-04 at 9 35 58 pm](https://user-images.githubusercontent.com/31792015/36947618-bc6c8a30-1ff4-11e8-8fbf-f9e6f6a5944b.png)

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
3 hours

**Comment by Tagsahil** [comment]
@sunjunkie  I want to work on it.

**Comment by sunjunkie** [comment]
Approved @Tagsahil
