### ISSUE TITLE
Name the unnamed segue in the project.

### ISSUE THREAD

**Issue by SIMRAN1** [systers/powerup-iOS#237]
## Description
As a developer,
I need to name the segues defined in  the project,
so that segue didnot throw nil value.Unamed segue throw nil value..

## Mocks
[INSERT RELEVANT PNG FILE]

## Acceptance Criteria
All unamed segues are named.
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours 
I want to work on this issue.

**Comment by SIMRAN1** [comment]
@sunjunkie May I proceed to work on this issue?

**Comment by sunjunkie** [comment]
Can you complete the template above? Specifically the Acceptance Criteria. Just enter  ‘not applicable’ for the other optional items that don’t apply.

**Comment by SIMRAN1** [comment]
okk @sunjunkie ..There are more than 1 unnamed segue..Ex when we move from CompletedViewController.swift to maps..

**Comment by sunjunkie** [comment]
Yes you can work on this. Also, replace the print statements with AssertionFailure in the appropriate switch statements as we previously discussed.

**Comment by SIMRAN1** [comment]
okk @sunjunkie mam I will work on it..
