### ISSUE TITLE
After Game completes

### ISSUE THREAD

**Issue by Tagsahil** [systers/powerup-iOS#240]
## Description
After completion of the game, there is no button or navigation screen which can reset the game.

## Mocks

![screen shot 2018-03-21 at 7](https://user-images.githubusercontent.com/31792015/37718364-87474064-2d48-11e8-8969-64b59b0e5e97.jpg)

## Acceptance Criteria
After game completion, new game or replay screen navigation occur or Reset Button occurs on StartView.
After pressing Reset Button it must show a warning message in it Confirm or Cancel button occurs.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours

**Comment by sunjunkie** [comment]
Can you provide more details? Perhaps some screenshots?  I’m also not sure why you reference the About menu.

**Comment by Tagsahil** [comment]
It's not necessary to add reset button in about button. 
We can add it in home menu or in map. 
I am removing idea about add reset button in About menu. @sunjunkie

**Comment by sunjunkie** [comment]
OK. I do still need more details.

**Comment by sunjunkie** [comment]
Please explain the function of the reset button and how it differs from the New Game button.
