### ISSUE TITLE
Add skip button to vocab matching game.

### ISSUE THREAD

**Issue by SIMRAN1** [systers/powerup-iOS#241]
## Description
A user who has already played the game before or is re-playing it might wish to skip reading the tutorial every time. Thus, adding a "skip tutorial" button would allow the user, who already knows how to play the game, to directly start playing the game.

## Mocks
[INSERT RELEVANT PNG FILE]

## Acceptance Criteria
skip button is added
### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2  hours

**Comment by SIMRAN1** [comment]
@sunjunkie please see to this issue.

**Comment by sunjunkie** [comment]
This was fixed for all tutorials in https://github.com/systers/powerup-iOS/issues/142. Please document the exact steps for getting the error (tutorial).

**Comment by SIMRAN1** [comment]
@sunjunkie mam  I mean to say that if a user plays the game again ..For ex user heads back to map and then click home button and then create new avatar and play game so if user is already familiar with the steps.Hence to make game more attractive we should add skip button ..What do u think?

**Comment by sunjunkie** [comment]
This would be a new feature which is a low priority now. You are welcome to suggest new features in GSoC proposal.

**Comment by SIMRAN1** [comment]
okk @sunjunkie
