### ISSUE TITLE
Updating How to Contribute Guidelines.

### ISSUE THREAD

**Issue by SIMRAN1** [systers/powerup-iOS#249]
## Description
As a developer I need to know proper contributing guidelines so that I can get a proper direction for contribution to project.

## Acceptance Criteria
How to contribute Guidelines are updated.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by SIMRAN1** [comment]
@sunjunkie mam for wiki edit "How to contribute guidelines" I have made a repo in github https://github.com/SIMRAN1/powerup-iOS-wiki   .Please review it and suggest changes.I have made changes according to android wiki documentation.

**Comment by SIMRAN1** [comment]
@sunjunkie mam this is updated How to Contribute guidlines for https://github.com/SIMRAN1/powerup-iOS-wiki/blob/master/How-To-Contribute.md  .Please review it and suggest changes.

**Comment by sunjunkie** [comment]
Changes have been moved to the wiki page.
