### ISSUE TITLE
Create controller and model to describe and present intro and outro sequences

### ISSUE THREAD

**Issue by justKD** [systers/powerup-iOS#256]
## Description
As a developer,
I need to create a controller class and model that will describe and present intro and outro sequences,
so that I can ensure specifications to add this content are clear and and the content is usable, and to conform to efficient model-controller principles.

## Mocks
n/a

### Update [Required]
- [ ] owns references to all necessary media
- [ ] describes and handles order of events
- [ ] describes and handles interactions and visual feedback
- [ ] story sequence class retrieves data from a model
- [ ] the ui gives a visual indication that the user should interact with the screen in order to move forward

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sunjunkie** [comment]
implemented via PR #273
