### ISSUE TITLE
Swift 4.1 deprecations

### ISSUE THREAD

**Issue by justKD** [systers/powerup-iOS#263]
## Description
As a developer,
I need to update deprecated code,
so that I can remove unnecessary compiler warnings and avoid future issues.

## Mocks
<img width="272" alt="screen shot 2018-05-17 at 9 54 27 pm" src="https://user-images.githubusercontent.com/24572031/40213840-315335a8-5a1d-11e8-9996-ced331c5b146.png">

### Update [Required]
- [ ] String interpolation produces a debug description for an optional value; did you mean to make this explicit?
- [ ] 'characters' is deprecated: Please use String or Substring directly
- [ ] 'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' operator.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sunjunkie** [comment]
Fixed by PR #275
