### ISSUE TITLE
Intro class does not interfere with scenario launch

### ISSUE THREAD

**Issue by justKD** [systers/powerup-iOS#265]
## Description
As a developer,
I need the intro story sequence to not change the way scenarios are already launched,
so that I can ensure it can be safely managed without breaking other game content.

### Update [Required]
- [ ] Intro sequence can be invoked by simply overlaying a view on the existing view controller
- [ ] Disables interactions on the existing vc
- [ ] Re-enables interactions once the intro view is disposed

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sunjunkie** [comment]
Fixed via PR #271
