### ISSUE TITLE
Drop support for iOS 9

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#288]
## Description
As a developer,
I want to drop support for iOS 9,
so that I can remove unnecessary code.

## Notes:
As of June 5, 2018, 95% of iOS devices are running iOS 10/11 and iOS 12 is coming out this fall. (iOS tends to have a high rate of upgrade adoption.) iOS 10 is compatible with iPhone 5 and later.

### Update [Required]
- [ ] project supports iOS 10 and above
- [ ] all availability conditions that test for ios version 9 (or 10+) are removed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by hashah88** [comment]
Can I work on this issue?

**Comment by anubhavpulkit** [comment]
Can I look upon this?

**Comment by sunjunkie** [comment]
Superceded by issue #331
