### ISSUE TITLE
Instructions/indicator for skipping a story sequence

### ISSUE THREAD

**Issue by justKD** [systers/powerup-iOS#306]
## Description
As a user,
I need an indicator that automated story sequences can be skipped via long press,
so that I can know about the convenience/accessibility function.

### Update [Required]
- [ ] Add brief instruction indicating the functionality when a story sequence opens

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sunjunkie** [comment]
Fixed via PR #310
