### ISSUE TITLE
Character avatar bug

### ISSUE THREAD

**Issue by sarayd** [systers/powerup-iOS#37]
![screen shot 2016-12-19 at 10 38 00 am](https://cloud.githubusercontent.com/assets/16440070/21324593/44ae7508-c5d7-11e6-81f9-8f18614b16a5.png)
![screen shot 2016-12-19 at 10 37 54 am](https://cloud.githubusercontent.com/assets/16440070/21324592/44abd8a2-c5d7-11e6-815a-bdaae96f6013.png)

**Comment by YashBit** [comment]
@sanyajain  Is this okay ?
https://github.com/systers/powerup-iOS/pull/41

**Comment by sanyajain** [comment]
@YashBit There is no overlapping of hairstyles but the neck disappears. I am attaching its screenshot. 
![screen shot 2017-01-07 at 1 23 07 pm](https://cloud.githubusercontent.com/assets/11500519/21740325/d431b118-d4dc-11e6-8ae3-6597e5de9750.png)

**Comment by YashBit** [comment]
Ok , I will improve interface 
. But do the new images overlay on background 1 or is it just the hair image ?
