### ISSUE TITLE
Newly created Avatar not saved

### ISSUE THREAD

**Issue by sanyajain** [systers/powerup-iOS#40]
In certain instances of the game, newly created character is not saved and only body framework of Avatar is displayed. This usually happens when we click Start button to go to a previous instance of the game. 

![screen shot 2017-01-03 at 1 34 40 am](https://cloud.githubusercontent.com/assets/11500519/21595554/22398df8-d155-11e6-9929-b328f196ad35.png)
![screen shot 2017-01-03 at 1 46 15 am](https://cloud.githubusercontent.com/assets/11500519/21595672/7a596476-d156-11e6-8c92-a3371750ad7c.png)
![screen shot 2017-01-03 at 1 46 27 am](https://cloud.githubusercontent.com/assets/11500519/21595675/866a92a8-d156-11e6-9928-e9c96e376e52.png)

**Comment by YashBit** [comment]
@sanyajain Can this task be assigned to me ?

**Comment by YashBit** [comment]
@sanyajain  So this happens when we have created a new user . After that we go back to the start screen and then go to the map right ?

**Comment by sanyajain** [comment]
@YashBit When you click on Start button and go to level-1 and 2, then this happens

**Comment by YashBit** [comment]
@sanyajain Sorry , I just need some clarification . This bug is related to when a new user has been created . And then the user goes to the start screen and then level 1 or 2  right ?
I have this condition because anyways when a user Is not created all the default images are the ones without the head . So the problems is even though the user has created a new user all the default images return due to the fact that the gamer went back to the start screen ?

**Comment by sanyajain** [comment]
@YashBit The way this is supposed to work is as follows:
New User creates a new Avatar and the user can play the levels with that Avatar. When user goes to the Start Screen, if you hit Start- previously created Avatar appears on the screen and previous instance of the game is restored. If you hit New User, you create a new Avatar and a fresh game can be played(with the newly created Avatar). 
Now, if you open the game for the first time and press Start, an error message should pop up telling you to hit New User first. I am attaching a screenshot for your reference
![screen shot 2016-08-20 at 3 01 59 pm](https://cloud.githubusercontent.com/assets/11500519/21776124/004933fa-d6bf-11e6-9de6-5939be6d6aee.png)
 (This is from the code which was latest modified in August by me). 
This functionality doesn't work in the latest code. That has some bugs primarily related to the use of Start button. Right now the bug appears when you're playing levels and then go back to Start screen and hit 'Start'. If you hit New User, you can again create an Avatar and play and then the head doesn't disappear. 
I am sorry, this is a bit confusing. You will get more idea when you test the app thoroughly yourself. Additionally, go through section 6 of the documentation [here](https://docs.google.com/document/d/1N_-zmmjPn6D1H6wTdF4z66mFGT3af_FWbfGvLKkeY1w/edit?usp=sharing)

**Comment by YashBit** [comment]
@sanyajain  Is this okay ?
https://github.com/systers/powerup-iOS/pull/49

**Comment by sunjunkie** [comment]
Fixed by #74
