### ISSUE TITLE
Design Issue in iPhone 7 and iPhone 7 Plus

### ISSUE THREAD

**Issue by sanyagithub** [systers/powerup-iOS#53]
iPhone 7
![screen shot 2017-01-15 at 3 03 19 pm](https://cloud.githubusercontent.com/assets/5487176/21961602/f7e00030-db33-11e6-823d-0df89817a045.png)
iPhone 7 Plus
![screen shot 2017-01-15 at 3 03 44 pm](https://cloud.githubusercontent.com/assets/5487176/21961606/029447ca-db34-11e6-8baa-15e4dcfaad22.png)

**Comment by Aviral190694** [comment]
Hi, I would like to solve this bug. Though we need a discussion regarding this specific bug because till the date there is no Autolayout constraint being set. I set the background parameters well. It looks fine right now but as the code and game improves we need more auto layout constraints.

**Comment by sunjunkie** [comment]
Initial fix in PR #67
