### ISSUE TITLE
The code should be restructured

### ISSUE THREAD

**Issue by casd82** [systers/powerup-iOS#56]
Currently, the question sets and scenes are rather hard-coded. There are many classes with almost the same code. (especially the classes below)

![2017-03-01 10 10 14](https://cloud.githubusercontent.com/assets/12479866/23465585/ac4be7ec-fed3-11e6-8485-15f143c09d30.png)

The multiple "Choices" UIControlViews should be rewritten in one.

**Comment by Aviral190694** [comment]
Yes, Also a Class is also required which handles the Database operations. Currently, every controller has database code which is unnecessary.

**Comment by Aviral190694** [comment]
Yes. I too want to edit a couple of things. The project needs some work. There is no Autolayout in the storyboard. There is no use of having a Navigation Controller in the beginning.

**Comment by yashnak2** [comment]
(I am a GSoC aspirant)
I would restructure the code by having one Choices class where all of the repetitive code is written in this one class, and each scene inherits from it. This would increase code readability and efficiency.

**Comment by sunjunkie** [comment]
Covered in #71
