### ISSUE TITLE
Layout issues in iPad .

### ISSUE THREAD

**Issue by rathishubham7** [systers/powerup-iOS#57]
![simulator screen shot 14-mar-2017 3 30 37 am](https://cloud.githubusercontent.com/assets/16849485/23877160/fa3396fc-0866-11e7-974c-46797d1021de.png)
As you can see there is layout issue in iPad( also #53 ). i'd like to add autolayout parameters to it . should i submit a PR for this ?

**Comment by rathishubham7** [comment]
I am a GSoC student . Can i sumbit a PR for this ?

**Comment by Aviral190694** [comment]
@rathishubham7 are you referenced this issue is exactly similar to https://github.com/systers/powerup-iOS/issues/53.  The storyboard needs Autolayout for every view. I did the Auto layout but can't push the code yet. Soon iOS mentors will be available to let us push :)

**Comment by rathishubham7** [comment]
ok great . :)
