### ISSUE TITLE
Error in Creating an Avatar for a new User.

### ISSUE THREAD

**Issue by yvsssantosh** [systers/powerup-iOS#58]
**Steps to reproduce the bug**

1. Install app for the first time.

2. Click on **Start** button
     (We will get an alert asking to create a new user)

3.  Click on **New User** button

4. Navigate back to the home page without creating a user.

5. Click on **Start Button**
     
6. Navigates to the map but the user is not created ... Resulting an inappropriate user image.

The following is the screenshot showing the above mentioned bug.

![screen shot 2017-03-21 at 1 10 17 am](https://cloud.githubusercontent.com/assets/11535830/24118571/42eaac60-0dd4-11e7-81bb-4188f34313ce.png)

(Since the user is not created .... It doesn't have a head.)

I would like to fix this bug.
Thank you :)

**Comment by vishesh9494** [comment]
I am a GSoC 2017 aspirant and am interested in solving this bug

**Comment by yvsssantosh** [comment]
@vishesh9494 Please kindly read the guidelines first before commenting.

**Comment by vishesh9494** [comment]
The guidelines stated commenting on a bug in the issues section. And you previously did not mention that you are a GSoC aspirant. So I commented here. I am sorry but I already sent a pull request regarding this.

**Comment by yvsssantosh** [comment]
@vishesh9494 I already mentioned that i'll work on this issue and was waiting for the mentor's approval. Once a mentor approves then I'll go with this issue. 

That is the reason I mentioned to read the guidelines because the owner of the issue gets the right to put a PR and if he/she is not active with the issue then you can put a PR.

That's how it goes in systers
Hope you understand :)
Thanks for the reply

**Comment by Aviral190694** [comment]
@vishesh9494 @yvsssantosh No worries guys. The app has enough bugs to be resolved and modules to be created that everyone has fair chance to show what talent they have.
@vishesh9494 A note I want to make is No one is allowed to send PR's without getting the bug marked to self that's the reason I asked in the slack so that you can read it. I know we all are passionate about the projects and want to get into GSOC but lets keep the competition healthy. There are people who are contributing from months and then some are doing from last month. I hope you all don't mind it :)

**Comment by pandilladivya** [comment]
@vishesh9494 

You should wait until the mentors approve the issue.
And moreover this issue was raised by @yvsssantosh and he already mentioned that he will be working on that . So I think you need to get the issue assigned to you before solving it.

Happy coding guys :)

**Comment by vishesh9494** [comment]
I am really sorry everyone! I am not very familiar with this and so did this in haste. Sorry for the inconvenience. Thank you for making me realise this mistake this early 😅.

**Comment by Aviral190694** [comment]
@vishesh9494 No worries :)
