### ISSUE TITLE
Level 1 ending should have a Portrait screen

### ISSUE THREAD

**Issue by yvsssantosh** [systers/powerup-iOS#59]
**Steps to reproduce**

1. Open the PowerUp iOS app and click on **Start** button

2. Enter level 1 from map and play the level

3. Depending on various responses the level will reach to a conclusion

4. The last screen gets tilted automatically tilted to Landscape view than Portrait view

Here is the last screen
![screen shot 2017-03-21 at 2 54 30 am](https://cloud.githubusercontent.com/assets/11535830/24137076/19317e76-0e38-11e7-97df-4ed73a5d5ff2.png)

**Comment by Aviral190694** [comment]
@yvsssantosh I don't think so this is a bug at all. This is an added functionality as the designer here wants to show the updation of health, powers and user karma. 
Though we should prefer to keep whole app either landscape or portrait.

**Comment by yvsssantosh** [comment]
@Aviral190694 
I think it indicates inconsistency in the app and needs to be taken care of.
Please correct me if I am wrong :)
