### ISSUE TITLE
Need a single class file for FMDB wrapper and Data models for different Database queries.

### ISSUE THREAD

**Issue by Aviral190694** [systers/powerup-iOS#60]
Currently, every controller open the database and then query and parse the results in the controller itself which should be done via a single class or a singleton class to be apt as data won't change. 

I am a GSOC'17 Student. I have implemented Autolayout as well and want to submit PR regarding the same.

**Comment by sunjunkie** [comment]
If you work on this, stay focused on the database. The Autolayout will be a separate issue.

**Comment by sunjunkie** [comment]
Subsumed under #70
