### ISSUE TITLE
.DS_Store should be included in git ignore file

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#61]
On macOS X, the .DS_Store file should not be under version control. It's an OS-generated file and not part of the source code. It should be removed from the repo and an entry added to the .gitignore file.

**Comment by yvsssantosh** [comment]
@sunjunkie Is it okay if i work on this issue?

I'm a GSoC 2017 aspirant and would like to work on it :)

**Comment by sunjunkie** [comment]
@yvsssantosh Yes, go ahead. Besides editing .gitignore file you will also have to remove all the .DS_store files in the repo. I think there are four.

**Comment by yvsssantosh** [comment]
I've added a pull request
Please review :)

Thank You
