### ISSUE TITLE
Newly updated gitIgnore file should be this : https://github.com/github/gitignore/blob/master/Swift.gitignore

### ISSUE THREAD

**Issue by Aviral190694** [systers/powerup-iOS#64]
This is the template provided by Github and takes care of every case. As the project will grow we will be using Pods for sure.

**Comment by Aviral190694** [comment]
I am a GSOC aprirant and can send a PR for this.

**Comment by sunjunkie** [comment]
I don't think it is useful to transfer that entire .gitignore to this project. There are items there that we don't need and some macOS-specific items that we use are missing. Take a look at the swift, OSX, and Xcode .gitignore files and then propose specific additions to our .gitignore that you think are appropriate.
