### ISSUE TITLE
User completes the Home Scenario.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-iOS#75]
**Description**

As a player, I want to complete the "Store" scenario,
so that I can earn karma points and buy new things!

**Mocks**

Borrow the Phone
![image](https://user-images.githubusercontent.com/399376/27214279-68478fd8-5220-11e7-8405-6011c3267228.png)

**Acceptance Criteria**

User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**

Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
TBD

**Comment by sunjunkie** [comment]
I moved the scenario from the Store to Home per our last meeting.
