### ISSUE TITLE
User completes the Library Scenario

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#86]
**Description**

As a player,
I want to complete the "Library" scenario,
so that I can earn karma points and buy new things!

**Mocks**

Puberty Research
![image](https://user-images.githubusercontent.com/399376/26983457-b461bfd6-4cf0-11e7-9a5e-eb6e5619eb92.png)

**Acceptance Criteria**

User interacts with an NPC.
Once conversation is finished, user is notified with the # of karma points earned.

**Definition of Done**

Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
TBD

**Comment by codingblazer** [comment]
@casd82 If you are creating .csv file for these, then directly use the .csv from my PR in Android version. Repeating same work won't be productive. :-)

**Comment by casd82** [comment]
@codingblazer Thanks a lot!!
