### ISSUE TITLE
Allow avatar customization

### ISSUE THREAD

**Issue by madeleine-b** [systers/powerup-iOS#9]

**Comment by jenpaff** [comment]
@sanyajain Please add a more detailed description: what are the main changes? is there a PR link? would also be useful to add labels and milestone it belongs to.

**Comment by sanyajain** [comment]
@jenpaff Thanks for the suggestion. Done (y)

**Comment by sanyajain** [comment]
Following functionalities have been added:
1. Creation of dressing room-1 that appears after the user clicks on "New User" on Start Screen. The user can customise the Avatar look by choosing eyes, hair, clothes, face for the Avatar. 
The link to PR: https://github.com/systers/powerup-iOS/pull/20    
Following are the screenshots of the dressing room screen-1:
![screen shot 2016-06-11 at 3 04 24 am](https://cloud.githubusercontent.com/assets/11500519/16179274/07668818-367e-11e6-8ae3-20bd5e4ec78e.png)
![screen shot 2016-06-11 at 3 04 52 am](https://cloud.githubusercontent.com/assets/11500519/16179277/1583b0ba-367e-11e6-8385-e399151e86b1.png)
![screen shot 2016-06-11 at 3 05 12 am](https://cloud.githubusercontent.com/assets/11500519/16179278/159fc6e2-367e-11e6-8d75-c7913ee52224.png)
![screen shot 2016-06-11 at 3 05 42 am](https://cloud.githubusercontent.com/assets/11500519/16179279/15a081f4-367e-11e6-89e0-fd44892434e4.png)

**Comment by sanyajain** [comment]
Implemented in PR #21 .
@jenpaff I think this issue can be closed now.
