### ISSUE TITLE
Developer needs UI elements for the minesweeper game.

### ISSUE THREAD

**Issue by jenpaff** [systers/powerup-iOS#92]
## Description
As a developer,
I want to code the minesweeper game,
so that I can code it into the sex scenario.

## Mocks
![screen shot 2017-06-10 at 20 37 50](https://user-images.githubusercontent.com/2440938/27007308-b6b833c8-4e1c-11e7-8031-03201fe71230.png)

## Acceptance Criteria
- Red, Green, and White Dots all consistent.
- Winning Screen
- Losing Screen

## Definition of Done
- Passes user testing per acceptance criteria items.
- Featured in design meeting.
- Approved by UI team. (Dil & May)

## Estimation
5 Hours

**Comment by kimhwins** [comment]
it would be really cool to have a card flip animation when the player taps on a star!
