### ISSUE TITLE
Handle all error conditions appropriately

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#93]
**Description**

As a user,
I want the app to handle errors appropriately without crashing.

**Acceptance Criteria**

Errors that the app cannot correct will either notify the user (without crashing), and/or fail silently if the game is still able to continue.

**Definition of Done**

Passes unit testing of error conditions.

**Estimation**
tbd

**Comment by jenpaff** [comment]
Covered with PR #97
