### ISSUE TITLE
User cannot purchase 2 accessories of the same type.

### ISSUE THREAD

**Issue by sunjunkie** [systers/powerup-iOS#95]
**Description**

As an User,
I want to be able to click on several accessories of the same type when shopping without karma points being deducted for each click,
so that I see how each accessory of that type looks and decide which one I like better.

**Mocks**
N/A

**Acceptance Criteria**

User clicks on an accessor to purchase it and karma points are deducted.
User clicks on another one of the **same** accessory type.
The avatar is changed but no additional karma points are deducted.

**Definition of Done**

Passes all regression tests.
Passes testing per acceptance criteria items.
Approved by UI team.
Able to show feature in demo.

**Estimation**
tbd

**Comment by casd82** [comment]
What I'm thinking is to add a "price sum" label indicating the summed price of the chosen accessories and a "purchase button". The purchase will succeed and the Karma points will be deducted only after the "purchased button" is clicked. This approach would solve both #94 and #95. How do you think?

**Comment by casd82** [comment]
I solved this and issue #94 in PR #98.
